[WIP] VE-2045: add an api call for collecting metrics
hyperledger/indy-sdk pull request #2255
Opened 2020-10-20 13:29 UTC by Toktar

2020-10-22 12:46 UTC, skhoroshavin requested changes

2020-10-22 12:46 UTC, skhoroshavin commented on libindy/src/api/metrics.rs
> +/// It allows to avoid expensive key derivation for use cases when wallet keys can be stored in a secure enclave.
I think this needs to be updated

2020-10-22 12:46 UTC, skhoroshavin commented on libindy/src/api/metrics.rs
> +                                                            key: *const c_char)>) -> ErrorCode {
This should return list of key-value pairs, not a single string

2020-10-22 12:46 UTC, skhoroshavin commented on libindy/src/api/metrics.rs
> +    trace!("indy_generate_wallet_key: params config: {:?}", secret!(config.as_ref()));
I suspect these are also left-overs from code that was taken as a template...

2020-10-22 12:46 UTC, skhoroshavin commented on libindy/src/commands/metrics.rs
> +    open_callbacks: RefCell<HashMap<CommandHandle, Box<dyn Fn(IndyResult<PoolHandle>)>>>,
Do we really use/need these callbacks, or they are also leftovers from wallet command executor?

2020-10-22 15:05 UTC, skhoroshavin commented on libindy/src/commands/metrics.rs
> +        debug!("collecting metrics from the current thread");
```suggestion
        debug!("collecting metrics from command thread");
```

2020-10-23 14:49 UTC, skhoroshavin approved these changes

2020-10-23 14:56 UTC, jovfer requested changes

2020-10-23 14:56 UTC, jovfer commented on libindy/src/commands/metrics.rs
> +        let res = serde_json::to_string(&metrics_map).unwrap();
```suggestion
        let res = serde_json::to_string(&metrics_map)?;
```

2020-10-23 15:29 UTC, jovfer approved these changes

2020-10-25 11:43 UTC, merged